name: Credo

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-coveralls-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-coveralls-
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 27.2
          elixir-version: 1.18.0
      - run: mix deps.get
      - run: MIX_ENV=test mix credo